name: CI/CD - Build and Deploy Docker Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker (optionnel si registry privée)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-portfolio:latest .

      - name: Save Docker image as artifact (optionnel)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: |
            ./Dockerfile
            # tu peux sauvegarder aussi l'image si tu veux transférer le tar
            # docker save my-portfolio:latest -o my-portfolio.tar

  deploy:
    name: Deploy Docker image on server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Dockerfile to server via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "Dockerfile"
          target: "/home/${{ secrets.SERVER_USER }}/myporfolio"
          rm: true

      - name: Build and run Docker container on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/myporfolio
            docker build -t my-portfolio:latest .
            docker stop my-portfolio || true
            docker rm my-portfolio || true
            docker run -d -p 80:80 --name my-portfolio my-portfolio:latest
