name: CI/CD - Build and Deploy Docker Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-portfolio:latest .

      - name: Save Docker image to tar
        run: |
          docker save my-portfolio:latest -o my-portfolio.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-portfolio.tar

  deploy:
    name: Deploy Docker image on server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Copy Docker image to server via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "my-portfolio.tar"
          target: "/home/${{ secrets.SERVER_USER }}/myporfolio"

      - name: Load and run Docker container on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/myporfolio
            docker load -i my-portfolio.tar
            docker stop my-portfolio || true
            docker rm my-portfolio || true
            docker run -d -p 80:80 --name my-portfolio my-portfolio:latest
